
input:
  i3s : /share/des/disc7/samuroff/des/y1a1-im3shape-v6-infocuts.fits
  hoopoe : /share/des/disc8/cambridge/bord-fits/combined_cats/hoopoe-ohio_A4_A6-infocuts-hv2-i3sv2-catv3-weights.fits

selection:
    mask : none #/share/des/disc8/cambridge/bord-fits/selection_masks/mask-ohio_A4_A6-infocuts-hv2-i3sv2-catv02-no_Rb_cut.fits
    reweight : False
    resample : False
    weights : True
    weights_file : none #/share/des/disc8/cambridge/cal/no_box_cut/weights//data-hoopoe_weights_column-v6_extra.fits

calibration:
  method : grid
  rbins : 16
  sbins : 16
  ztype : des
  split : none

output :
    histograms : False
    alpha : False
    snr : False
    redshift : True
    tables : False
    half_tables : False
    filename: y1a1-nbc-grid-im3shape-r-1-2-6.fits
    dir : /share/des/disc8/cambridge/cal/interpolated_weights
